server:
    port: 8080
    routes:
        /auth:
            algorithm: least_connection
            backends:
                - http://localhost:8081
                - http://localhost:8082

        /api:
            algorithm: least_connection
            backends:
                - http://localhost:8091
